DIMENSIONS = [
    "LNG", "BIG_OIL", "RENEWABLES", "RUSSIA",
    "CHINA", "US_POLICY", "EU_UKRAINE", "SANCTIONS_TARIFFS",
    "ISRAEL"
]

DEFAULT_MODEL = "gemini-2.5-flash-lite"
AXES_SNIPPET_MAX = 120
NARRATIVE_SNIPPET_MAX = 25
AXES_BUCKET_LIMIT = 50
PROMPT_AXES_LINES_LIMIT = 40
PROMPT_NARRATIVE_LINES_LIMIT = 15
